---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: rebel-base
  namespace: default
spec:
  service: rebel-base
  backends:
  - service: rebel-base
    weight: 50
  - service: rebel-base-kind-c1
    weight: 50
